### ISSUE TITLE
scheduler crashed

### ISSUE THREAD

**Issue by AntoineNGUYEN31** [EtangDesApplis/green-hand#3]
kubectl -n green-hands logs pod/daemons-bdd789569-gt755
[2020-12-12][22:20:39][INFO] sent verification email to user with id = 1
Traceback (most recent call last):
  File "/app/scheduler.py", line 95, in <module>
    daemon.run()
  File "/app/scheduler.py", line 89, in run
    self.scheduleEvents()
  File "/app/scheduler.py", line 70, in scheduleEvents
    timeStamp=int(datetime.now().strftime("%Y"))*100+int(month)
ValueError: invalid literal for int() with base 10: ''
[2020-12-12][22:21:06][INFO] sending notifications to user with id = 1

**Comment by AntoineNGUYEN31** [comment]
fixed since 1.0.1
